apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels:
    app: todoapp 
    role: frontend 
spec:
  selector:
    matchLabels:
      app: todoapp
      role: frontend
  replicas: 1
  minReadySeconds : 10
  template:
    metadata:
      name: todoapp
      labels:
        app: todoapp 
        role: frontend  
      spec:
        containers:
        - name: todoapp
          image: charlecr.azurecr.io/todoapp:0.0.2
          ports:
          - containerPort: 3000
            port: 3000
          imagePullPolicy: Allways
        imagePullSecrets: 
          name: myregistrykey
        
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  type: LoadBalancer
  selector:
    app: todoapp
    role: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000